### ISSUE TITLE
Preloading assets too shortly in advance can lead to double fetch

### ISSUE THREAD

**Issue by tobimori** [craftedbygc/taxi#13]
**Describe the bug**
When preloading a page in advance, it will only be added to the cache as soon as the fetch is completed. This means, if the Navigation is started soon after, it'll try to fetch the page again instead of waiting for the preloaded entry to finish downloading.

Ideally, I want to be able to preload a page, and then let the Navigation use that preloaded page even if it starts before preloading is finished, so no content gets downloaded twice.

**Why?**
Starting preloading pages as soon as the user hovers over a link can lead to a lower loading time, as most users need 100-200ms to actually click a link upon hovering. This pattern is something I'd like to implement yet can't because of this constraint.

**To Reproduce**

1. Preload an URL
2. Navigate to the same page shortly after
3. Taxi will fire two requests

**Comment by jakewhiteley** [comment]
Hi @tobimori 

For a short while, hovering over links did actually prefetch just as your are, but this issue cropped up.

I could never recreate it however, and couldn't track down the specific browser condition causing it to happen so I abandoned the fix.

I believe the approach to solve would be to have a pool of requests, and upon navigation check if a pending request exists in the pool for the target URL. If it does, then we wait for that to resolve instead of creating a new fetch promise.

I can write this update, but would you be willing to help me test it?

**Comment by tobimori** [comment]
yes of course! would be glad to get this to work

**Comment by tobimori** [comment]
Just tested it, works great for me!

**Comment by jakewhiteley** [comment]
Yeah I didn't rebuild the typings for this test. What IDE are you using? VS?

I'll push it to npm shortly as a new version (with typings of course).

**Comment by tobimori** [comment]
yeah vs code

**Comment by jakewhiteley** [comment]
Done - [v1.3.0](https://github.com/craftedbygc/taxi/releases/tag/1.3.0)

I'm going to close this issue, but please feel free to reopen if you find any issues 💪
